apiVersion: apps/v1
kind: Deployment
metadata:
  name: dap-svc
  namespace: prototype
  labels:
    app: dap-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dap-service
  template:
    metadata:
      labels:
        app: dap-service
    spec:
      volumes:
      - name: dap-svc-overrides
        secret:
          secretName: dap-svc-overrides-staging
      containers:
      - name: dap-service-container
        image: 961839081442.dkr.ecr.us-east-1.amazonaws.com/dap-service@sha256:e8249c8d02b9d4ef8bf0264b2bb120c0b85470b0ff7ea52b4ec50aeb8becbd01
        env:
          - name: NODE_ENV
            value: staging
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "yarn start | npx bunyan" ]
        ports:
        - containerPort: 3000
        volumeMounts:
            - name: dap-svc-overrides
              mountPath: "/etc/trax-document-microservices"
              readOnly: true