apiVersion: v1
kind: Service
metadata: 
  name: einvoices-service
  namespace: prototype

  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector: 
    app: einvoices-service
  ports: 
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
